// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69IDa-_MoR0quoMD6VRyQFEXEQpdWa5M',
    appId: '1:73884408290:web:015b640bdd4882bdcc01bb',
    messagingSenderId: '73884408290',
    projectId: 'database-mobile-app-project',
    authDomain: 'database-mobile-app-project.firebaseapp.com',
    storageBucket: 'database-mobile-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYXlQYbQthU3ydKrPepXxm4JWwqrqN3DE',
    appId: '1:73884408290:android:a4f0a0ebad1ac151cc01bb',
    messagingSenderId: '73884408290',
    projectId: 'database-mobile-app-project',
    storageBucket: 'database-mobile-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwydXzBfyou4hA39I_ozYSK_CYIkP3EEE',
    appId: '1:73884408290:ios:df5a74b89a6eb273cc01bb',
    messagingSenderId: '73884408290',
    projectId: 'database-mobile-app-project',
    storageBucket: 'database-mobile-app-project.appspot.com',
    iosBundleId: 'com.example.appWhaletreat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwydXzBfyou4hA39I_ozYSK_CYIkP3EEE',
    appId: '1:73884408290:ios:df5a74b89a6eb273cc01bb',
    messagingSenderId: '73884408290',
    projectId: 'database-mobile-app-project',
    storageBucket: 'database-mobile-app-project.appspot.com',
    iosBundleId: 'com.example.appWhaletreat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69IDa-_MoR0quoMD6VRyQFEXEQpdWa5M',
    appId: '1:73884408290:web:b752b5d16a810ddfcc01bb',
    messagingSenderId: '73884408290',
    projectId: 'database-mobile-app-project',
    authDomain: 'database-mobile-app-project.firebaseapp.com',
    storageBucket: 'database-mobile-app-project.appspot.com',
  );
}
